name: Deploy to Preproduction

on:
  push:
    branches:
      - main

jobs:
  deploy-preprod:
    name: Deploy to Preproduction
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Preprod
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_PREPROD_SERVER }}
          username: ${{ secrets.FTP_PREPROD_USERNAME }}
          password: ${{ secrets.FTP_PREPROD_PASSWORD }}
          exclude: |
            /vendor/
            .git/
            node_modules/

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.O2SWITCH_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
      - name: Verify SSH key on runner
        run: |
          echo "Start of key:"
          head -n 5 ~/.ssh/id_rsa
          echo "..."
          echo "End of key:"
          tail -n 5 ~/.ssh/id_rsa

