name: Deploy to Preproduction

on:
  push:
    branches:
      - main

jobs:
  deploy-preprod:
    name: Deploy to Preproduction
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy to Preprod
        env:
          SSH_PRIVATE_KEY: ${{ secrets.O2SWITCH_SSH_PRIVATE_KEY }}
          DEPLOY_PATH_PREPROD: ${{ secrets.DEPLOY_PATH_PREPROD }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H o2switch.net >> ~/.ssh/known_hosts
          rsync -avz --delete --exclude='.env' ./ "$DEPLOY_PATH_PREPROD"

      - name: Clean up cache on server
        env:
          DEPLOY_PATH_PREPROD: ${{ secrets.DEPLOY_PATH_PREPROD }}
        run: |
          ssh o2switch.net "cd $DEPLOY_PATH_PREPROD && php artisan config:clear && php artisan cache:clear && php artisan route:clear"
