name: Deploy to Preproduction

on:
  push:
    branches:
      - main

jobs:
  deploy-preprod:
    name: Deploy to Preproduction
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy to Preprod
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_PREPROD_SERVER }}
          username: ${{ secrets.FTP_PREPROD_USERNAME }}
          password: ${{ secrets.FTP_PREPROD_PASSWORD }}
